spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Mysql123#root
    url: jdbc:mysql://localhost:3306/ies
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true